#!/bin/sh -f
# ****************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Thu May 30 22:37:55 EDT 2019
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************

# installation path setting
bin_path="/home/opt/synopsys/vcs-mx/N-2017.12-SP2-2/bin"

# directory path for design sources and include directories (if any) wrt this path
origin_dir="."

# set vhdlan command line args
vhdlan_opts="-full64"

# set vlogan command line args
vlogan_opts="-full64 -sverilog"

# compile design source files
$bin_path/vlogan $vlogan_opts +v2k -work xil_defaultlib  +incdir+$origin_dir/../../../../cnn.acc.bfp.ip_user_files/ipstatic/hdl/verilog \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/ip_buf_1/sim/ip_buf_1.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/ip_buf_0/sim/ip_buf_0.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/conv_buf/sim/conv_buf.v" \
2>&1 | tee -a vlogan.log

$bin_path/vhdlan $vhdlan_opts -work xil_defaultlib  \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/float_adder/sim/float_adder.vhd" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/float_multiply_adder/sim/float_multiply_adder.vhd" \
2>&1 | tee -a vhdlan.log

$bin_path/vlogan $vlogan_opts +v2k -work xil_defaultlib  +incdir+$origin_dir/../../../../cnn.acc.bfp.ip_user_files/ipstatic/hdl/verilog \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/bram_A/sim/bram_A.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/bram_B/sim/bram_B.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/of_blkmem/sim/of_blkmem.v" \
2>&1 | tee -a vlogan.log

$bin_path/vhdlan $vhdlan_opts -work xil_defaultlib  \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/adder_3/sim/adder_3.vhd" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/adder_2/sim/adder_2.vhd" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/adder_1/sim/adder_1.vhd" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/ip/mult2/sim/mult2.vhd" \
2>&1 | tee -a vhdlan.log

$bin_path/vlogan $vlogan_opts +v2k -work xil_defaultlib  +incdir+$origin_dir/../../../../cnn.acc.bfp.ip_user_files/ipstatic/hdl/verilog \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/LZC.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/bram_buffer.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/bram_conv_rd.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/bram_conv_wr.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/bram_data.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/bram_ddr_rd.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/bram_pooling_rd.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/buf_sel.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/conv.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/conv_op.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/sim/conv/data_pcie.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/ddr_iface_arbiter.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/sim/conv/ddr_mem.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/export_data.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/fc.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/fixed_max.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/fixed_to_float.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/float_to_fixed.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/float_to_fixed_bias.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/fsm.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/inner_product.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/ip_control_fm.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/ip_mem_interface.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/ip_mul_add_block_fm.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/ip_param_buf.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/ip_param_buf_control.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/ip_rd_data.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/max_1x49.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/max_1x64.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/mem_data.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/mem_ker.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/mem_patch_bram.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/mem_patch_rd.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/mem_patch_update.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/mem_top.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/pe_array1x3.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/pe_array3x3.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/rd_ddr_data.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/rd_ddr_exp.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/rd_ddr_op.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/rd_ddr_param.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/rd_wr_path.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/vgg.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/vgg_conv.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/fc/vgg_fc.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/src/conv/wr_ddr_data.v" \
"$origin_dir/../../../../cnn.acc.bfp.srcs/sources_1/sim/conv/board.tb.v" \
2>&1 | tee -a vlogan.log


# compile glbl module
$bin_path/vlogan $vlogan_opts +v2k -work xil_defaultlib "glbl.v" 2>&1 | tee -a vlogan.log
