#!/bin/sh -f
# ****************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 12 21:12:37 CST 2018
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************

# installation path setting
bin_path="/home/opt/synopsys/vcs-mx/N-2017.12-SP2-2/bin"



# set top_simv command line args
top_simv_opts="+vpdfile+top.vpd" #+vpdfilesize+2048"

# run simulation
./top_simv $top_simv_opts +dump_all | tee simulation.txt
